version: '3.8'

networks:
  frontend:
  backend:


services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./volume-mysql:/var/lib/mysql
      - ./_mysql_init:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=strongpass
      - bind-address=0.0.0.0

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 4400:5000
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
